/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GameGui;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author ACER
 */
public class FormGame extends javax.swing.JFrame {
    GamePlay play = new GamePlay(0,0);
    ImageIcon gunting = new ImageIcon("gunting2.JPG");
    ImageIcon batu = new ImageIcon("batu2.JPG");
    ImageIcon kertas = new ImageIcon("kertas.JPG");
    int ronde,akhir;
    String name;
    FormRonde round = new FormRonde();
    
    
    /**
     * Creates new form FormGame
     */
    public FormGame(int batas, String nama) {
        initComponents();
        akhir = batas;
        name = nama;
        setLocationRelativeTo(null);
        setResizable(false);
        tRound.setEditable(false);
        tNumber.setEditable(false);
        lNama.setText(name);
        ronde = 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lGambarYou = new javax.swing.JLabel();
        lGambarCom = new javax.swing.JLabel();
        lskorYou = new javax.swing.JLabel();
        lskorCom = new javax.swing.JLabel();
        lhasil = new javax.swing.JLabel();
        bGunting = new javax.swing.JButton();
        bBatu = new javax.swing.JButton();
        bKertas = new javax.swing.JButton();
        lNama = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tRound = new javax.swing.JTextField();
        tNumber = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(101, 14, 122));

        lGambarYou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GameGui/batu2.JPG"))); // NOI18N

        lGambarCom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GameGui/batu2.JPG"))); // NOI18N

        lskorYou.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lskorYou.setForeground(new java.awt.Color(255, 255, 255));
        lskorYou.setText("0");

        lskorCom.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lskorCom.setForeground(new java.awt.Color(255, 255, 255));
        lskorCom.setText("0");

        lhasil.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lhasil.setForeground(new java.awt.Color(255, 255, 255));
        lhasil.setText("READY !");

        bGunting.setBackground(new java.awt.Color(153, 0, 0));
        bGunting.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bGunting.setForeground(new java.awt.Color(255, 255, 255));
        bGunting.setText("GUNTING\n");
        bGunting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuntingActionPerformed(evt);
            }
        });

        bBatu.setBackground(new java.awt.Color(0, 51, 255));
        bBatu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bBatu.setForeground(new java.awt.Color(255, 255, 255));
        bBatu.setText("BATU");
        bBatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatuActionPerformed(evt);
            }
        });

        bKertas.setBackground(new java.awt.Color(255, 204, 0));
        bKertas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bKertas.setForeground(new java.awt.Color(255, 255, 255));
        bKertas.setText("KERTAS");
        bKertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKertasActionPerformed(evt);
            }
        });

        lNama.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lNama.setForeground(new java.awt.Color(255, 255, 255));
        lNama.setText("YOU");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("COMPUTER");

        tRound.setBackground(new java.awt.Color(255, 102, 102));
        tRound.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tRound.setForeground(new java.awt.Color(255, 255, 255));
        tRound.setText("RONDE");

        tNumber.setBackground(new java.awt.Color(0, 153, 153));
        tNumber.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tNumber.setForeground(new java.awt.Color(255, 255, 255));
        tNumber.setText("1");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lGambarYou)
                .addGap(45, 45, 45)
                .addComponent(lskorYou, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lskorCom, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lGambarCom)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(tRound, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lhasil)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bGunting)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bBatu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bKertas)))
                        .addContainerGap(372, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(lNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNama)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lGambarYou, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lGambarCom, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tRound))
                        .addGap(134, 134, 134)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lskorCom)
                            .addComponent(lskorYou)
                            .addComponent(lhasil))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGunting)
                    .addComponent(bBatu)
                    .addComponent(bKertas))
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGuntingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuntingActionPerformed
        // TODO add your handling code here:
        ronde++;
        lGambarYou.setIcon(gunting);
        if (play.getCom().equals("g")) {
            lGambarCom.setIcon(gunting);
        }else if (play.getCom().equals("b")) {
            lGambarCom.setIcon(batu);
        }else if (play.getCom().equals("k")) {
            lGambarCom.setIcon(kertas);
        }
        play.setYou("g");
        play.seleksiHasil();
        lskorYou.setText(Integer.toString(play.getSkorYou()));
        lskorCom.setText(Integer.toString(play.getSkorCom()));
        lhasil.setText(play.getHasil());
        play.pindahPos();   
        if (ronde == akhir) {
            play.totHasil();
            JOptionPane.showMessageDialog(this, play.getHasil(), "Info", JOptionPane.INFORMATION_MESSAGE);
            int dialog = JOptionPane.showConfirmDialog(this, "APAKAH KAMU LANJUT ?");
            if (dialog == JOptionPane.YES_OPTION) {
                setVisible(false);
                round.setVisible(true);
            }else{
                dispose();
            }
          
        }
        tNumber.setText(Integer.toString(ronde + 1));
    }//GEN-LAST:event_bGuntingActionPerformed

    private void bBatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatuActionPerformed
        // TODO add your handling code here:
        ronde++;
        lGambarYou.setIcon(batu);
        if (play.getCom().equals("g")) {
            lGambarCom.setIcon(gunting);
        }else if (play.getCom().equals("b")) {
            lGambarCom.setIcon(batu);
        }else if (play.getCom().equals("k")) {
            lGambarCom.setIcon(kertas);
        }
        play.setYou("b");
        play.seleksiHasil();
        lskorYou.setText(Integer.toString(play.getSkorYou()));
        lskorCom.setText(Integer.toString(play.getSkorCom()));
        lhasil.setText(play.getHasil());
        play.pindahPos();     
         if (ronde == akhir) {
            play.totHasil();
            JOptionPane.showMessageDialog(this, play.getHasil(), "Info", JOptionPane.INFORMATION_MESSAGE);
            int dialog = JOptionPane.showConfirmDialog(this, "APAKAH KAMU LANJUT ?");
            if (dialog == JOptionPane.YES_OPTION) {
                setVisible(false);
                round.setVisible(true);
            }else{
                dispose();
            }
          
        }
        tNumber.setText(Integer.toString(ronde + 1));
    }//GEN-LAST:event_bBatuActionPerformed

    private void bKertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKertasActionPerformed
        // TODO add your handling code here:
        ronde++;
        lGambarYou.setIcon(kertas);
        if (play.getCom().equals("g")) {
            lGambarCom.setIcon(gunting);
        }else if (play.getCom().equals("b")) {
            lGambarCom.setIcon(batu);
        }else if (play.getCom().equals("k")) {
            lGambarCom.setIcon(kertas);
        }
        play.setYou("k");
        play.seleksiHasil();
        lskorYou.setText(Integer.toString(play.getSkorYou()));
        lskorCom.setText(Integer.toString(play.getSkorCom()));
        lhasil.setText(play.getHasil());
        play.pindahPos();
        if (ronde == akhir) {
            play.totHasil();
            JOptionPane.showMessageDialog(this, play.getHasil(), "Info", JOptionPane.INFORMATION_MESSAGE);
            int dialog = JOptionPane.showConfirmDialog(this, "APAKAH KAMU LANJUT ?");
            if (dialog == JOptionPane.YES_OPTION) {
                setVisible(false);
                round.setVisible(true);
            }else{
                dispose();
            }
          
        }
        tNumber.setText(Integer.toString(ronde + 1));
    }//GEN-LAST:event_bKertasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(this, "Yakin Ingin Keluar ? ");
        if (exit == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "YOU LOSERR!!", "INFO", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatu;
    private javax.swing.JButton bGunting;
    private javax.swing.JButton bKertas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lGambarCom;
    private javax.swing.JLabel lGambarYou;
    private javax.swing.JLabel lNama;
    private javax.swing.JLabel lhasil;
    private javax.swing.JLabel lskorCom;
    private javax.swing.JLabel lskorYou;
    private javax.swing.JTextField tNumber;
    private javax.swing.JTextField tRound;
    // End of variables declaration//GEN-END:variables
}
